package DCMSSystem.CenterServerOrb.CenterServicePackage;


/**
* CenterServerOrb/CenterServicePackage/except.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIDL.idl
* Wednesday, July 11, 2018 11:38:39 o'clock AM EDT
*/

public final class except extends org.omg.CORBA.UserException
{
  public String reason = null;

  public except ()
  {
    super(exceptHelper.id());
  } // ctor

  public except (String _reason)
  {
    super(exceptHelper.id());
    reason = _reason;
  } // ctor


  public except (String $reason, String _reason)
  {
    super(exceptHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class except
