package DCMSSystem.CenterServerOrb.CenterServicePackage;

/**
* CenterServerOrb/CenterServicePackage/exceptHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIDL.idl
* Wednesday, July 11, 2018 11:38:39 o'clock AM EDT
*/

public final class exceptHolder implements org.omg.CORBA.portable.Streamable
{
  public except value = null;

  public exceptHolder ()
  {
  }

  public exceptHolder (except initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = exceptHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    exceptHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return exceptHelper.type ();
  }

}
