package DCMSSystem.CenterServerOrb;


/**
* CenterServerOrb/listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIDL.idl
* Wednesday, July 11, 2018 11:38:39 o'clock AM EDT
*/

public final class listHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public listHolder ()
  {
  }

  public listHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return listHelper.type ();
  }

}
