package CenterServerOrb.CenterServerPackage;

/**
* CenterServerOrb/CenterServerPackage/exceptHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerOrb.idl
* Tuesday, June 12, 2018 11:36:58 o'clock AM EDT
*/

public final class exceptHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerOrb.CenterServerPackage.except value = null;

  public exceptHolder ()
  {
  }

  public exceptHolder (CenterServerOrb.CenterServerPackage.except initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerOrb.CenterServerPackage.exceptHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerOrb.CenterServerPackage.exceptHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerOrb.CenterServerPackage.exceptHelper.type ();
  }

}
