package CenterServerOrb;

/**
* CenterServerOrb/CenterServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIDL.idl
* Wednesday, July 11, 2018 11:38:39 o'clock AM EDT
*/

public final class CenterServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterServerOrb.CenterService value = null;

  public CenterServiceHolder ()
  {
  }

  public CenterServiceHolder (CenterServerOrb.CenterService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterServerOrb.CenterServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterServerOrb.CenterServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterServerOrb.CenterServiceHelper.type ();
  }

}
