package CenterServerOrb;


/**
* CenterServerOrb/CenterServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerIDL.idl
* Wednesday, July 11, 2018 11:38:39 o'clock AM EDT
*/

public interface CenterServiceOperations 
{
  String createTRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerId, String firstName, String lastName, String[] courseRegistered, String status, String statusDate);
  String getRecordCounts (String managerId);
  String editRecord (String managerId, String recordID, String fieldName, String newValue) throws CenterServerOrb.CenterServicePackage.except;
  String transferRecord (String managerId, String recordID, String remoteCenterServerName) throws CenterServerOrb.CenterServicePackage.except;
  void shutdown ();
} // interface CenterServiceOperations
