package CenterServerOrb;


/**
* CenterServerOrb/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerOrb.idl
* Saturday, June 9, 2018 12:05:53 o'clock PM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
